name: deploy

on:
  workflow_dispatch:
    inputs:
      GIT_BRANCH:
        description: 'branch to clone'
        required: true
        default: 'main'
      GIT_REPO:
        description: 'customer repo name (e.g. next-web-starterkit)'
        required: true
      ENVIRONMENT:
        type: choice
        description: 'target environment to deploy to'
        required: true
        options:
          - STAGING
          - PRODUCTION
      CONVOX_RACK:
        description: 'convox rack name'
        required: true
      CONVOX_APP:
        description: 'convox app name'
        required: true
      CUSTOM_CONVOX_DOMAIN:
        description: 'custom convox domain (leave empty if not applicable)'
        required: false
        default: ''
      OPERATION:
        type: choice
        description: 'action to perform (deploy=build & deploy, upgrade=in place upgrade)'
        required: true
        default: 'deploy'
        options:
          - deploy
          - upgrade
      TEAMS_SUCCESS_WEBHOOK_URL:
        description: 'Teams webhook URL for success notifications'
        required: true
      TEAMS_FAILURE_WEBHOOK_URL:
        description: 'Teams webhook URL for failure notifications'
        required: true

run-name: >
  ${{ github.event.inputs.GIT_REPO }} . ${{ github.event.inputs.GIT_BRANCH }} . ${{ github.event.inputs.OPERATION }} . ${{ github.event.inputs.ENVIRONMENT }}

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: setup node 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: install yarn
        run: npm install --global yarn

      - name: install convox cli
        run: |
          curl -L https://github.com/convox/convox/releases/latest/download/convox-linux -o /tmp/convox
          sudo mv /tmp/convox /usr/local/bin/convox
          chmod 755 /usr/local/bin/convox
          convox version

      - name: Get Current Job Log URL
        uses: Tiryoh/gha-jobid-action@v0
        id: jobs
        with:
          github_token: ${{ secrets.GH_PASSWORD }}
          job_name: ${{ github.job }}

      - name: write boot.env
        run: |
          sudo tee /boot.env > /dev/null <<EOF
          BRANCH_TO_BUILD=${{ github.event.inputs.GIT_BRANCH }}
          REPO_TO_FETCH=github.com/atex-ci/${{ github.event.inputs.GIT_REPO }}.git
          CONVOX_RACK=${{ github.event.inputs.CONVOX_RACK }}
          CONVOX_APP=${{ github.event.inputs.CONVOX_APP }}
          CONVOX_TOKEN=${{ secrets.CONVOX_TOKEN }}
          CUSTOM_CONVOX_DOMAIN=${{ github.event.inputs.CUSTOM_CONVOX_DOMAIN }}
          GH_USERNAME=${{ github.repository_owner }}
          GH_PASSWORD=${{ secrets.GH_PASSWORD }}
          TEAMS_SUCCESS_WEBHOOK_URL=${{ github.event.inputs.TEAMS_SUCCESS_WEBHOOK_URL }}
          TEAMS_FAILURE_WEBHOOK_URL=${{ github.event.inputs.TEAMS_FAILURE_WEBHOOK_URL }}
          JIRA_AUTH_TOKEN=${{ secrets.JIRA_AUTH_TOKEN }}
          PIPELINE=${{ github.event.inputs.OPERATION }}
          TARGET_ENV=${{ github.event.inputs.ENVIRONMENT }}
          STORYBOOK_LANGUAGE=
          STORYBOOK_URL=
          AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
          JOB_URL=${{ steps.jobs.outputs.html_url }}
          EOF

      - name: run boot.sh
        run: |
          git config --global http.sslverify false
          git clone --branch "${{ github.event.inputs.GIT_BRANCH }}" "https://${{ github.repository_owner }}:${{ secrets.GH_PASSWORD }}@github.com/atex-ci/${{ github.event.inputs.GIT_REPO }}.git" /tmp/next-web-checkout

          cd /tmp/next-web-checkout
          sed -i -e "s|github.com|${{ github.repository_owner }}:${{ secrets.GH_PASSWORD }}@github.com|g" .gitmodules
          git submodule update --init --recursive --quiet

          sudo cp /tmp/next-web-checkout/ci-cd/build-machine/boot.sh /boot.sh
          sudo chmod +x /boot.sh

          rm -rf /tmp/next-web-checkout
          cd /

          sudo -E /boot.sh
