name: publish-storybook

on:
  workflow_dispatch:
    inputs:
      GIT_BRANCH:
        description: 'branch to clone'
        required: true
        default: 'main'
      GIT_REPO:
        description: 'customer repo name (e.g. next-web-starterkit)'
        required: true
      S3_BUCKET:
        description: 's3 bucket for CI results'
        required: true
      STORYBOOK_LANGUAGE:
        description: 'storybook language'
        required: false
        default: 'en'
      STORYBOOK_URL:
        description: 'storybook URL'
        required: true

run-name: >
  ${{ github.event.inputs.GIT_REPO }} . ${{ github.event.inputs.GIT_BRANCH }} . publish-storybook

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: setup node 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: install yarn
        run: npm install --global yarn

      - name: ensure aws cli is present
        run: aws --version

      - name: authenticate aws cli
        run: |
          aws configure set aws_access_key_id "${{ secrets.AWS_ACCESS_KEY_ID }}"
          aws configure set aws_secret_access_key "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          aws configure set default.region eu-west-1

      - name: write boot.env
        run: |
          sudo tee /boot.env > /dev/null <<EOF
          BRANCH_TO_BUILD=${{ github.event.inputs.GIT_BRANCH }}
          REPO_TO_FETCH=github.com/atex-ci/${{ github.event.inputs.GIT_REPO }}.git
          CONVOX_RACK=
          CONVOX_APP=
          CUSTOM_CONVOX_DOMAIN=
          GH_USERNAME=${{ github.repository_owner }}
          GH_PASSWORD=${{ secrets.GH_PASSWORD }}
          TEAMS_SUCCESS_WEBHOOK_URL=${{ secrets.TEAMS_SUCCESS_WEBHOOK_URL }}
          TEAMS_FAILURE_WEBHOOK_URL=${{ secrets.TEAMS_FAILURE_WEBHOOK_URL }}
          JIRA_AUTH_TOKEN=${{ secrets.JIRA_AUTH_TOKEN }}
          PIPELINE=publish-storybook
          TARGET_ENV=
          STORYBOOK_LANGUAGE=${{ github.event.inputs.STORYBOOK_LANGUAGE }}
          STORYBOOK_URL=${{ github.event.inputs.STORYBOOK_URL }}
          S3_BUCKET=${{ github.event.inputs.S3_BUCKET }}
          AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
          EOF

      - name: run boot.sh
        run: |
          git config --global http.sslverify false
          git clone --branch "${{ github.event.inputs.GIT_BRANCH }}" "https://${{ github.repository_owner }}:${{ secrets.GH_PASSWORD }}@github.com/atex-ci/${{ github.event.inputs.GIT_REPO }}.git" /tmp/next-web-checkout

          cd /tmp/next-web-checkout
          sed -i -e "s|github.com|${{ github.repository_owner }}:${{ secrets.GH_PASSWORD }}@github.com|g" .gitmodules
          git submodule update --init --recursive --quiet

          sudo cp /tmp/next-web-checkout/ci-cd/build-machine/boot.sh /boot.sh
          sudo chmod +x /boot.sh

          rm -rf /tmp/next-web-checkout

          sudo -E /boot.sh
